# Generated by Django 4.1.5 on 2023-03-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0003_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='assigned_patients',
            field=models.ManyToManyField(blank=True, null=True, related_name='responsible_providers', to='ehr.patient'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
