# Generated by Django 4.1.5 on 2023-03-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0007_patient_photo_alter_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
