# Generated by Django 4.1.5 on 2023-03-09 00:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0008_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vital',
            name='diastolic_bp',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='vital',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.patient'),
        ),
        migrations.AddField(
            model_name='vital',
            name='pulse',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(220)]),
        ),
        migrations.AddField(
            model_name='vital',
            name='spo2',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(88), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='vital',
            name='systolic_bp',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(220)]),
        ),
    ]
