# Generated by Django 4.1.5 on 2023-03-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0010_problem_diagnosis_problem_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy',
            name='allergen',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='allergy',
            name='patient',
            field=models.ManyToManyField(related_name='allergies', to='ehr.patient'),
        ),
        migrations.AddField(
            model_name='allergy',
            name='reaction',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='allergy',
            name='severity',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Moderate'), ('H', 'High')], max_length=1, null=True),
        ),
    ]
