# Generated by Django 4.1.5 on 2023-03-09 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0011_allergy_allergen_allergy_patient_allergy_reaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='dose',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9000)]),
        ),
        migrations.AddField(
            model_name='medication',
            name='dose_units',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='medication',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='medication',
            name='patient',
            field=models.ManyToManyField(related_name='meds', to='ehr.patient'),
        ),
    ]
