# Generated by Django 4.1.5 on 2023-03-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0012_medication_dose_medication_dose_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='allergen',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='reaction',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='diagnosis',
            field=models.CharField(default='', max_length=100),
        ),
    ]
