# Generated by Django 4.1.5 on 2023-03-11 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0016_alter_doctor_assigned_patients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vital',
        ),
    ]
