# Generated by Django 4.1.5 on 2023-03-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0017_delete_vital'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='sort_preference',
            field=models.CharField(choices=[('Default', 'Default'), ('First Name', 'First Name'), ('Last Name', 'Last Name'), ('Age', 'Age')], default='Default', max_length=10),
        ),
    ]
