# Generated by Django 4.1.5 on 2023-03-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0018_doctor_sort_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
